/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.GestionClientes;
import javax.swing.JOptionPane;
import negocio.Cliente;
import util.RHException;

/**
 *
 * @author by
 */
public class RegistroCliente extends javax.swing.JFrame {
    private GestionClientes gc;
    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
        gc = new GestionClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroLabel = new javax.swing.JLabel();
        nombresLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        nombresInput = new javax.swing.JTextField();
        telefonoInput = new javax.swing.JTextField();
        apellidosLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        correoInput = new javax.swing.JTextField();
        apellidosInput = new javax.swing.JTextField();
        tipoDocLabel = new javax.swing.JLabel();
        contrasenaLabel = new javax.swing.JLabel();
        tipoDocumentoComboBox = new javax.swing.JComboBox<>();
        contrasenaInput = new javax.swing.JTextField();
        numeroDocLabel = new javax.swing.JLabel();
        confirmarLabel = new javax.swing.JLabel();
        numeroDocInput = new javax.swing.JTextField();
        confirmarInput = new javax.swing.JTextField();
        crearCuentaButton1 = new javax.swing.JButton();
        crearCuentaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registroLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        registroLabel.setText("Registro");

        nombresLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nombresLabel.setText("Nombres");

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        telefonoLabel.setText("Teléfono");

        nombresInput.setToolTipText("");

        telefonoInput.setToolTipText("");

        apellidosLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        apellidosLabel.setText("Apellidos");

        correoLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        correoLabel.setText("Correo electrónico");
        correoLabel.setToolTipText("");

        tipoDocLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tipoDocLabel.setText("Tipo documento");

        contrasenaLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        contrasenaLabel.setText("Contraseña");

        tipoDocumentoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "TI" }));

        numeroDocLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        numeroDocLabel.setText("Número de documento");

        confirmarLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        confirmarLabel.setText("Confirmar contraseña");

        crearCuentaButton1.setBackground(new java.awt.Color(51, 102, 255));
        crearCuentaButton1.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton1.setText("Crear cuenta");
        crearCuentaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButton1ActionPerformed(evt);
            }
        });

        crearCuentaButton.setBackground(new java.awt.Color(255, 102, 102));
        crearCuentaButton.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton.setText("Actualizar");
        crearCuentaButton.setActionCommand("Crear cuenta");
        crearCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(crearCuentaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(crearCuentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(registroLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombresLabel)
                            .addGap(175, 175, 175)
                            .addComponent(telefonoLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombresInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(telefonoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(apellidosLabel)
                            .addGap(178, 178, 178)
                            .addComponent(correoLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(apellidosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(correoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipoDocLabel)
                            .addGap(143, 143, 143)
                            .addComponent(contrasenaLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipoDocumentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(contrasenaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numeroDocLabel)
                            .addGap(107, 107, 107)
                            .addComponent(confirmarLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numeroDocInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(confirmarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearCuentaButton1)
                    .addComponent(crearCuentaButton))
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(registroLabel)
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombresLabel)
                        .addComponent(telefonoLabel))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombresInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefonoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(apellidosLabel)
                        .addComponent(correoLabel))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(apellidosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(correoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tipoDocLabel)
                        .addComponent(contrasenaLabel))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tipoDocumentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(contrasenaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numeroDocLabel)
                        .addComponent(confirmarLabel))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numeroDocInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 79, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCuentaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButton1ActionPerformed
      try {
        // Collecting data from the form's input fields
        String tipoId = (String) tipoDocumentoComboBox.getSelectedItem();
        long id = Long.parseLong(numeroDocInput.getText());
        String nombre = nombresInput.getText();
        String apellido = apellidosInput.getText();
        long telefono = Long.parseLong(telefonoInput.getText());
        String correo = correoInput.getText();
        String contrasena = contrasenaInput.getText();
        String contrasenaConfirmacion = confirmarInput.getText();

        // Check if the passwords match
        if (!contrasena.equals(contrasenaConfirmacion)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Creating a new client
        gc.registrarCliente(tipoId, id, nombre, apellido, telefono, correo, contrasena);
            JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese datos válidos", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (RHException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_crearCuentaButton1ActionPerformed

    private void crearCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButtonActionPerformed
     try {
        // Assuming you have the client's ID stored or input in a field named idInput
        long id = Long.parseLong(numeroDocInput.getText()); // or from a different input field if needed
        long nuevoTelefono = Long.parseLong(telefonoInput.getText());
        String nuevoCorreo = correoInput.getText();

        // Updating the client's contact details
        gc.actualizarDatosContacto(id, nuevoTelefono, nuevoCorreo);
        JOptionPane.showMessageDialog(this, "Datos de contacto actualizados exitosamente", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese datos válidos", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (RHException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos de contacto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosInput;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JTextField confirmarInput;
    private javax.swing.JLabel confirmarLabel;
    private javax.swing.JTextField contrasenaInput;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JTextField correoInput;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JButton crearCuentaButton1;
    private javax.swing.JTextField nombresInput;
    private javax.swing.JLabel nombresLabel;
    private javax.swing.JTextField numeroDocInput;
    private javax.swing.JLabel numeroDocLabel;
    private javax.swing.JLabel registroLabel;
    private javax.swing.JTextField telefonoInput;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel tipoDocLabel;
    private javax.swing.JComboBox<String> tipoDocumentoComboBox;
    // End of variables declaration//GEN-END:variables
}
