/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import modelo.Servicio;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.GestionServicio;
import util.RHException;
import vista.customer.Customer;
/**
 *
 * @author Santiago
 */
public class MensajeroMain extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */

    public MensajeroMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        quickfavLogo = new javax.swing.JLabel();
        busarLabel = new javax.swing.JLabel();
        realizarButton = new javax.swing.JButton();
        serviciosButton = new javax.swing.JButton();
        historialButton = new javax.swing.JButton();
        buscarInput = new javax.swing.JTextField();
        lineLabel = new javax.swing.JLabel();
        serviciosLabel = new javax.swing.JLabel();
        realizarServiciosPanel = new javax.swing.JScrollPane();
        serviciosContainerPanel = new javax.swing.JPanel();
        container = new javax.swing.JLabel();
        
        historialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                System.out.println("click");
                //Customer customer = new Customer();
                //customer.setVisible(true);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 510));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quickfavLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/quickfavlogo.png"))); // NOI18N
        getContentPane().add(quickfavLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        busarLabel.setText("Buscar");
        getContentPane().add(busarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        realizarButton.setText("Realizar servicios");
        realizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(realizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        serviciosButton.setText("Mis servicios");
        getContentPane().add(serviciosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        historialButton.setText("Historial");
        getContentPane().add(historialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));
        getContentPane().add(buscarInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 80, -1));

        lineLabel.setForeground(new java.awt.Color(204, 204, 204));
        lineLabel.setText("_____________________________________________________________________________________________________________________________________________\n");
        getContentPane().add(lineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 720, -1));

        serviciosLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serviciosLabel.setText("Servicios disponibles");
        getContentPane().add(serviciosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 82, -1, -1));

        realizarServiciosPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        serviciosContainerPanel.setLayout(new java.awt.GridLayout(1, 2));
        realizarServiciosPanel.setViewportView(serviciosContainerPanel);

        getContentPane().add(realizarServiciosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 520, 250));

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/panel.png"))); // NOI18N
        container.setMaximumSize(new java.awt.Dimension(464, 412));
        container.setMinimumSize(new java.awt.Dimension(464, 412));
        container.setOpaque(true);
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void realizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarButtonActionPerformed
        try {
            // TODO carga todos los servicios disponibles
            GestionServicio gs = new GestionServicio();
            ArrayList<Servicio> serviciosSinAsignar = gs.consultarServicioSinAsignar();
            //GridLayout gridLayout = new GridLayout(serviciosSinAsignar.size() / 2, 2);
            GridLayout gridLayout = new GridLayout(0, 2);
            
            gridLayout.setHgap(50);
            gridLayout.setVgap(80);
            serviciosContainerPanel.setLayout(gridLayout);
            for (Servicio servicio : serviciosSinAsignar) {
                if (servicio.getEstado().equals("SOLICITADO")) {
                    System.out.println(servicio.getIdServicio());
                    JPanel comp = new JPanel();
                    comp.setLayout(new BorderLayout());
                    comp.setBackground(Color.WHITE);
                    comp.setPreferredSize(new Dimension(150, 150));
                    JLabel nombreServicio = new JLabel(servicio.getTipoPaquete());
                    JLabel imgServicio = new JLabel();
                    ImageIcon servicioImagen = new ImageIcon(getClass().getResource("Im1.png"));
                    Image scaledImage = servicioImagen.getImage().getScaledInstance(230, 80, Image.SCALE_SMOOTH);
                    servicioImagen = new ImageIcon(scaledImage);
                    imgServicio.setIcon(servicioImagen);
                    JButton aceptarServicio = new JButton("Aceptar servicio");
                    aceptarServicio.setName(String.valueOf(servicio.getIdServicio()));
                    aceptarServicio.addActionListener(new ActionListener() {
                        
                        @Override
                        public void actionPerformed(ActionEvent e){
                            System.out.println(aceptarServicio.getName());
                            int aceptar = JOptionPane.showConfirmDialog(null, "Seguro que quiere aceptar este servicio?", "Aceptar servicio", JOptionPane.YES_NO_OPTION);
                            if(aceptar == 0){
                                //Aceptar servicio
                                System.out.println("Se ha aceptado el servicio");
                                System.out.println("Se actualiza la base de datos");
                            }
                        }
                    });
                    comp.add(imgServicio, BorderLayout.NORTH);
                    comp.add(nombreServicio, BorderLayout.CENTER);
                    comp.add(aceptarServicio, BorderLayout.SOUTH);
                    //comp.setBounds(50, 50, 100, 70);
                    serviciosContainerPanel.add(comp);
                    
                }
                
            }
            serviciosContainerPanel.revalidate();
            serviciosContainerPanel.repaint();
        } catch (RHException ex) {
            Logger.getLogger(MensajeroMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_realizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeroMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensajeroMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel busarLabel;
    private javax.swing.JTextField buscarInput;
    private javax.swing.JLabel container;
    private javax.swing.JButton historialButton;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JLabel quickfavLogo;
    private javax.swing.JButton realizarButton;
    private javax.swing.JScrollPane realizarServiciosPanel;
    private javax.swing.JButton serviciosButton;
    private javax.swing.JPanel serviciosContainerPanel;
    private javax.swing.JLabel serviciosLabel;
    // End of variables declaration                   
}
