/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Santiago
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        direccionTextField = new javax.swing.JTextField();
        nombresTextField = new javax.swing.JTextField();
        apellidosTextField = new javax.swing.JTextField();
        ciudadTextField = new javax.swing.JTextField();
        apellidosLabel = new javax.swing.JLabel();
        ciudadLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        nombresLabel = new javax.swing.JLabel();
        registroLabel = new javax.swing.JLabel();
        confirmarTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        contrasenaTextField = new javax.swing.JTextField();
        correoLabel = new javax.swing.JLabel();
        contrasenaLabel = new javax.swing.JLabel();
        confirmarLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        crearCuentaButton = new javax.swing.JButton();
        crearCuentaButton1 = new javax.swing.JButton();
        container = new javax.swing.JLabel();
        backdround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(direccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 196, -1));

        nombresTextField.setToolTipText("");
        getContentPane().add(nombresTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 196, -1));
        getContentPane().add(apellidosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 196, -1));
        getContentPane().add(ciudadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 196, -1));

        apellidosLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        apellidosLabel.setText("Apellidos");
        getContentPane().add(apellidosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        ciudadLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        ciudadLabel.setText("Ciudad");
        getContentPane().add(ciudadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        direccionLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        direccionLabel.setText("Dirección de residencia");
        getContentPane().add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        nombresLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nombresLabel.setText("Nombres");
        getContentPane().add(nombresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        registroLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        registroLabel.setText("Registro");
        getContentPane().add(registroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        getContentPane().add(confirmarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 196, -1));

        telefonoTextField.setToolTipText("");
        getContentPane().add(telefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 196, -1));
        getContentPane().add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 196, -1));
        getContentPane().add(contrasenaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 196, -1));

        correoLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        correoLabel.setText("Correo electrónico");
        correoLabel.setToolTipText("");
        getContentPane().add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        contrasenaLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        contrasenaLabel.setText("Contraseña");
        getContentPane().add(contrasenaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        confirmarLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        confirmarLabel.setText("Confirmar contraseña");
        getContentPane().add(confirmarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        telefonoLabel.setText("Teléfono");
        getContentPane().add(telefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        crearCuentaButton.setBackground(new java.awt.Color(255, 102, 102));
        crearCuentaButton.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton.setText("Cancelar");
        crearCuentaButton.setActionCommand("Crear cuenta");
        getContentPane().add(crearCuentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 196, -1));

        crearCuentaButton1.setBackground(new java.awt.Color(51, 102, 255));
        crearCuentaButton1.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton1.setText("Crear cuenta");
        getContentPane().add(crearCuentaButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 196, -1));

        container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/panel.png"))); // NOI18N
        container.setMaximumSize(new java.awt.Dimension(464, 412));
        container.setMinimumSize(new java.awt.Dimension(464, 412));
        container.setOpaque(true);
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 464, 412));

        backdround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/background_1.png"))); // NOI18N
        backdround.setToolTipText("");
        getContentPane().add(backdround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1148, 514));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JLabel backdround;
    private javax.swing.JLabel ciudadLabel;
    private javax.swing.JTextField ciudadTextField;
    private javax.swing.JLabel confirmarLabel;
    private javax.swing.JTextField confirmarTextField;
    private javax.swing.JLabel container;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JTextField contrasenaTextField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JButton crearCuentaButton1;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel nombresLabel;
    private javax.swing.JTextField nombresTextField;
    private javax.swing.JLabel registroLabel;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
