/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.customer.services;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Mensajero;
import modelo.Servicio;
import negocio.Controlador;
import utils.Subject;

/**
 *
 * @author dsola
 */
public class ServicesListPanel extends javax.swing.JPanel {

    Controlador controlador = new Controlador();
    public Subject subject = new Subject();
    private JButton botonFuncion;
    /**
     * Creates new form ServicesListPanel
     */
    public ServicesListPanel() {
        initComponents();
        displayServices();
    }
    
    public String getTipoServicio(String tipo){
        if(tipo.equals("P")) return "Pago de recibo";
        else if(tipo.equals("M")) return "Radicar documento";
        else return "Envío de paquetes";
    }
    
    private class ButtonRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof JButton) {
                return (JButton) value;
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    }
    
    public void displayServices() {
        try{
            List<Servicio> services = controlador.consultarServiciosPorIdCliente(456789123);
            System.out.println(services.get(0).getActividad().getDireccion());
            List<Mensajero> mensajeros = new ArrayList<>();
            
             // Crear la tabla con un modelo de datos
            String[] columnas = {"Id", "Tipo servicio", "Precio", "Fecha solicitud", "Mensajero", "Ver detalles"};
            Object[][] filas = new Object[services.size()][6];

            for (int i = 0; i < services.size(); i++) {
                mensajeros.add(controlador.consultarMensajeroPorId(services.get(i).getIdMensajero()));
                
                botonFuncion = new JButton("Realizar Función");
                
                filas[i][0] = services.get(i).getIdServicio();
                filas[i][1] = getTipoServicio(services.get(i).getTipoPaquete());
                filas[i][2] = services.get(i).getCosto();
                filas[i][3] = services.get(i).getF_solicitud();
                filas[i][4] = mensajeros.get(i).getNombre() + " " + mensajeros.get(i).getApellido();
                filas[i][5] = botonFuncion;
            }

            DefaultTableModel modelo = new DefaultTableModel(filas, columnas){
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Hacer que todas las celdas sean no editables
                    
                    return false;
                }
            };            
            tableServices.setDefaultRenderer(Object.class, new ButtonRenderer());
            tableServices.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    int col = tableServices.columnAtPoint(evt.getPoint());
                    if (col == 5) {
                        subject.notificarObservadores(services.get(tableServices.getSelectedRow()), mensajeros.get(tableServices.getSelectedRow()));
                    }
                    
                }
            });
            tableServices.setModel(modelo);
            tableServices.repaint();
        
        } catch(Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serviceListContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServices = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1440, 950));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 950));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 26)); // NOI18N
        jLabel1.setText("Mis solicitudes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 81, -1, -1));

        serviceListContainer.setBackground(new java.awt.Color(255, 255, 255));
        serviceListContainer.setAutoscrolls(true);
        serviceListContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo de paquete", "Costo", "Fecha de solicitud", "Mensajero", "Ver detalles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableServices.setRowHeight(40);
        jScrollPane1.setViewportView(tableServices);

        serviceListContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 650));

        jPanel1.add(serviceListContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 147, 850, 660));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 950));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel serviceListContainer;
    private javax.swing.JTable tableServices;
    // End of variables declaration//GEN-END:variables
}
