/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.customer.services;

import modelo.Mensajero;
import modelo.Servicio;
import negocio.Controlador;
import utils.Subject;
import utils.TextTransform;

/**
 *
 * @author dsola
 */
public class ServiceItemDetailsPanel extends javax.swing.JPanel {
    
    public Subject subject = new Subject();
    private Mensajero mensajero;
    private Servicio servicio;
    private Controlador controlador = new Controlador();
    /**
     * Creates new form serviceItemDetailsPanel
     */
     
    public void displayServiceData() {
        serviceNameLabel.setText(getTipoServicio(this.servicio.getTipoPaquete()));
        servicePriceLabel.setText(String.valueOf(this.servicio.getCosto()));
        serviceDateLabel.setText(this.servicio.getF_solicitud());
        serviceDeliverLabel.setText(this.mensajero.getNombre() + " " + this.mensajero.getApellido());
        System.out.println(this.mensajero.getNombre() + " " + this.mensajero.getApellido() + this.mensajero.getSexo());
    }
    
    public String getTipoServicio(String tipo){
        if(tipo.equals("P")) return "Pago de recibo";
        else if(tipo.equals("M")) return "Radicar documento";
        else return "Envío de paquetes";
    }

    public ServiceItemDetailsPanel(Servicio servicio) {
        initComponents();
        this.servicio = servicio;
        
        getMensajero();   
    }
    
    public void getMensajero() {
        try{
            Mensajero mensajero = controlador.consultarMensajeroPorId(this.servicio.getIdMensajero());
            /* Mensajero mensajero = new Mensajero();
            mensajero.setNombre("carlos");
            mensajero.setApellido("gomez"); */
            this.mensajero = mensajero;
            displayServiceData();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        serviceNameLabel = new java.awt.Label();
        servicePriceLabel = new javax.swing.JLabel();
        serviceName1 = new java.awt.Label();
        serviceName2 = new java.awt.Label();
        serviceName3 = new java.awt.Label();
        serviceDeliverLabel = new javax.swing.JLabel();
        serviceDateLabel = new javax.swing.JLabel();
        detailsServiceButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cancelServiceButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(233, 233, 233), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 246));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 246));

        imageContainer.setBackground(new java.awt.Color(255, 255, 255));
        imageContainer.setPreferredSize(new java.awt.Dimension(400, 146));
        imageContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/customer/services/bill.png"))); // NOI18N
        imageContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 76));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceNameLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        serviceNameLabel.setForeground(new java.awt.Color(52, 53, 61));
        serviceNameLabel.setText("Nombre servicio");
        jPanel3.add(serviceNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 10, -1, 20));

        servicePriceLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        servicePriceLabel.setForeground(new java.awt.Color(141, 141, 141));
        servicePriceLabel.setText("$25.000");
        jPanel3.add(servicePriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 36, -1, 20));

        serviceName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName1.setForeground(new java.awt.Color(52, 53, 61));
        serviceName1.setText("Encargado");
        jPanel3.add(serviceName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, 20));

        serviceName2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName2.setForeground(new java.awt.Color(52, 53, 61));
        serviceName2.setText("Costo");
        jPanel3.add(serviceName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 36, -1, 20));

        serviceName3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName3.setForeground(new java.awt.Color(52, 53, 61));
        serviceName3.setText("Duracion");
        jPanel3.add(serviceName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 62, -1, 20));

        serviceDeliverLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceDeliverLabel.setForeground(new java.awt.Color(141, 141, 141));
        serviceDeliverLabel.setText("Pepito perez");
        jPanel3.add(serviceDeliverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 87, -1, 20));

        serviceDateLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceDateLabel.setForeground(new java.awt.Color(141, 141, 141));
        serviceDateLabel.setText("1 hora y 24 minutos");
        jPanel3.add(serviceDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 62, -1, 20));

        detailsServiceButton.setBackground(new java.awt.Color(102, 119, 247));
        detailsServiceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        detailsServiceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailsServiceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsServiceButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                detailsServiceButtonMousePressed(evt);
            }
        });
        detailsServiceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/customer/services/alert-circle-outline.png"))); // NOI18N
        jLabel1.setText("Detalles");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        detailsServiceButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        jPanel3.add(detailsServiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 88, 36));

        cancelServiceButton.setBackground(new java.awt.Color(242, 46, 62));
        cancelServiceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        cancelServiceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelServiceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/customer/services/close.png"))); // NOI18N
        jLabel2.setText("Cancelar");
        cancelServiceButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        jPanel3.add(cancelServiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 88, 36));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 132, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 400, 246));
    }// </editor-fold>//GEN-END:initComponents

    private void detailsServiceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsServiceButtonMouseClicked
        
    }//GEN-LAST:event_detailsServiceButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void detailsServiceButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsServiceButtonMousePressed
        this.subject.notificarObservadores(this.servicio);
    }//GEN-LAST:event_detailsServiceButtonMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        this.subject.notificarObservadores(this.servicio);
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelServiceButton;
    private javax.swing.JPanel detailsServiceButton;
    private javax.swing.JPanel imageContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel serviceDateLabel;
    private javax.swing.JLabel serviceDeliverLabel;
    private java.awt.Label serviceName1;
    private java.awt.Label serviceName2;
    private java.awt.Label serviceName3;
    private java.awt.Label serviceNameLabel;
    private javax.swing.JLabel servicePriceLabel;
    // End of variables declaration//GEN-END:variables
}
