/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.customer.services;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Mensajero;
import modelo.Servicio;
import negocio.Controlador;
import utils.Constants;
import vista.customer.Customer;

/**
 *
 * @author dsola
 */
public class ServicesListPanel extends javax.swing.JPanel {

    Controlador controlador = new Controlador();
    private JTable tabla;
    private JButton botonFuncion;
    /**
     * Creates new form ServicesListPanel
     */
    public ServicesListPanel() {
        initComponents();
        displayServices();
    }
    
    public String getTipoServicio(String tipo){
        if(tipo.equals("P")) return "Pago de recibo";
        else if(tipo.equals("M")) return "Radicar documento";
        else return "Envío de paquetes";
    }
    
    public int[] getServicePanelCords (int index) {
        int espacioEntreComponentes = 50;
        int componentesPorFila = 2;

        int fila = index / componentesPorFila;
        int columna = index % componentesPorFila;

        int x = columna * (Constants.getItemXSize() + espacioEntreComponentes);
        int y = fila * (Constants.getItemYSize() + espacioEntreComponentes);

        return new int[]{x, y};
    }
    
    public void displayServices() {
        try{
            List<Servicio> services = controlador.consultarServiciosPorIdCliente(456789123);
            
             // Crear la tabla con un modelo de datos
            String[] columnas = {"Id", "Tipo servicio", "Precio", "Fecha solicitud", "Mensajero"};
            Object[][] filas = new Object[services.size()][5];

            for (int i = 0; i < services.size(); i++) {
                Mensajero mensajero = controlador.consultarMensajeroPorId(services.get(i).getIdMensajero());
                
                filas[i][0] = services.get(i).getIdServicio();
                filas[i][1] = getTipoServicio(services.get(i).getTipoPaquete());
                filas[i][2] = services.get(i).getCosto();
                filas[i][3] = services.get(i).getF_solicitud();
                filas[i][4] = mensajero.getNombre() + " " + mensajero.getApellido();
                System.out.println(services.get(i).getIdServicio());
            }

            DefaultTableModel modelo = new DefaultTableModel(filas, columnas);
            tabla = new JTable(modelo);

            // Añadir la tabla a un JScrollPane para que sea desplazable
            JScrollPane scrollPane = new JScrollPane(tabla);

            // Crear el botón
            botonFuncion = new JButton("Realizar Función");

            // Añadir un ActionListener al botón para manejar eventos
            botonFuncion.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Obtener la fila seleccionada
                    int filaSeleccionada = tabla.getSelectedRow();

                    // Verificar si se seleccionó alguna fila
                    if (filaSeleccionada != -1) {
                        // Obtener el objeto Datos correspondiente a la fila seleccionada
                        Servicio datoSeleccionado = services.get(filaSeleccionada);

                        // Realizar la función asociada al objeto Datos
                        
                    }
                }
            });

            // Crear un contenedor para organizar los componentes

            // Añadir la tabla y el botón al contenedor
            serviceListContainer.removeAll();
            serviceListContainer.add(scrollPane, BorderLayout.CENTER);
            serviceListContainer.add(botonFuncion, BorderLayout.SOUTH);
            serviceListContainer.revalidate();
            serviceListContainer.repaint();
        
        } catch(Exception e) {
            System.out.println(e);
        }

       
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serviceListContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1440, 950));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 950));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 26)); // NOI18N
        jLabel1.setText("Mis solicitudes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 81, -1, -1));

        serviceListContainer.setBackground(new java.awt.Color(255, 255, 255));
        serviceListContainer.setAutoscrolls(true);

        javax.swing.GroupLayout serviceListContainerLayout = new javax.swing.GroupLayout(serviceListContainer);
        serviceListContainer.setLayout(serviceListContainerLayout);
        serviceListContainerLayout.setHorizontalGroup(
            serviceListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        serviceListContainerLayout.setVerticalGroup(
            serviceListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(serviceListContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 147, 850, 660));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 950));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel serviceListContainer;
    // End of variables declaration//GEN-END:variables
}
