/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.customer.services;

import modelo.Mensajero;
import modelo.Servicio;
import negocio.Controlador;
import utils.Subject;
import vista.customer.Customer;

/**
 *
 * @author dsola
 */
public class ServiceDetailsPanel extends javax.swing.JPanel {
    
    public Subject subject = new Subject();
    Controlador controlador = new Controlador();
    
    private Mensajero mensajero;
    private Servicio servicio;
    /**
     * Creates new form serviceDetailsPanel
     */
    public ServiceDetailsPanel(Servicio servicio, Mensajero mensajero) {
        this.servicio = servicio;
        this.mensajero = mensajero;
        initComponents();
        displayData();
    }
    
    public String getTipoServicio(String tipo){
        if(tipo.equals("P")) return "Pago de recibo";
        else if(tipo.equals("M")) return "Radicar documento";
        else return "Envío de paquetes";
    }
    
    public String getTipoTransporte(String tipo){
        if(tipo.equals("B")) return "Bicicleta";
        else return "Motocicleta";
    }
    
    public void displayData(){
        serviceName.setText(getTipoServicio(this.servicio.getTipoPaquete()));
        servicePrice.setText(String.valueOf(this.servicio.getCosto()));
        serviceDate.setText(this.servicio.getF_solicitud());
        servicePrice.setText("Paco");
        servicePaymethod.setText("Efectivo");
        serviceReturn.setSelected(true);
        deliverName.setText(mensajero.getNombre() + " " + mensajero.getApellido());
        deliverVehicle.setText(getTipoTransporte(mensajero.getMedioTransporte()));
        //activityAdress.setText(servicio.getActividad().getDireccion());
        //activityDescription.setText("<html>" + servicio.getActividad().getDescripcionActividad() +"</html>");
        //activityDetails.setText("<html>" + servicio.getActividad().getDetallesDireccion()+"</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        activityDetails = new javax.swing.JLabel();
        activityDescription = new javax.swing.JLabel();
        serviceName17 = new java.awt.Label();
        serviceName18 = new java.awt.Label();
        activityAdress = new javax.swing.JLabel();
        serviceName7 = new java.awt.Label();
        serviceName2 = new java.awt.Label();
        serviceName3 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        dtails = new java.awt.Label();
        deliverVehicle = new javax.swing.JLabel();
        serviceName5 = new java.awt.Label();
        serviceName14 = new java.awt.Label();
        deliverName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        serviceName = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        serviceName8 = new java.awt.Label();
        serviceName10 = new java.awt.Label();
        servicePrice = new javax.swing.JLabel();
        serviceName11 = new java.awt.Label();
        servicePaymethod = new javax.swing.JLabel();
        serviceReturn = new javax.swing.JCheckBox();
        serviceName9 = new java.awt.Label();
        serviceDate = new javax.swing.JLabel();
        servicePrice1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1440, 950));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1145, 807));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 950));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/customer/services/arrow-back.png"))); // NOI18N
        jLabel1.setText("Atras");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(233, 233, 233), 2, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(340, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 238, 238), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activityDetails.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        activityDetails.setForeground(new java.awt.Color(141, 141, 141));
        activityDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        activityDetails.setText("<html>Descripcion</html>");
        activityDetails.setToolTipText("");
        activityDetails.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel6.add(activityDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 80));

        activityDescription.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        activityDescription.setForeground(new java.awt.Color(141, 141, 141));
        activityDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        activityDescription.setText("<html>Descripcion</html>");
        activityDescription.setToolTipText("");
        activityDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel6.add(activityDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 80));

        serviceName17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName17.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName17.setForeground(new java.awt.Color(52, 53, 61));
        serviceName17.setText("Descripcion");
        jPanel6.add(serviceName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        serviceName18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName18.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName18.setForeground(new java.awt.Color(52, 53, 61));
        serviceName18.setText("Descripcion del lugar");
        jPanel6.add(serviceName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 20));

        activityAdress.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        activityAdress.setForeground(new java.awt.Color(141, 141, 141));
        activityAdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        activityAdress.setText("Carrera xd");
        jPanel6.add(activityAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 210, 20));

        serviceName7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName7.setForeground(new java.awt.Color(52, 53, 61));
        serviceName7.setText("Direccion");
        jPanel6.add(serviceName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        serviceName2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        serviceName2.setForeground(new java.awt.Color(52, 53, 61));
        serviceName2.setText("Actividad #1");
        jPanel6.add(serviceName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 180));

        serviceName3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        serviceName3.setForeground(new java.awt.Color(52, 53, 61));
        serviceName3.setText("Direcciones");
        jPanel3.add(serviceName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 440, 290));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(233, 233, 233), 2, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dtails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dtails.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        dtails.setForeground(new java.awt.Color(52, 53, 61));
        dtails.setText("Detalles del servicio");
        jPanel2.add(dtails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        deliverVehicle.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        deliverVehicle.setForeground(new java.awt.Color(141, 141, 141));
        deliverVehicle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deliverVehicle.setText("deliverVehicle");
        deliverVehicle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(deliverVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 170, 20));

        serviceName5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName5.setForeground(new java.awt.Color(52, 53, 61));
        serviceName5.setText("Medio de transporte ayudante");
        jPanel2.add(serviceName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        serviceName14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName14.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName14.setForeground(new java.awt.Color(52, 53, 61));
        serviceName14.setText("Ayudante asignado");
        jPanel2.add(serviceName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        deliverName.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        deliverName.setForeground(new java.awt.Color(141, 141, 141));
        deliverName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deliverName.setText("Julano perez");
        deliverName.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(deliverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 440, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(233, 233, 233), 2, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(340, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        serviceName.setForeground(new java.awt.Color(52, 53, 61));
        serviceName.setText("Nombre servicio");
        jPanel4.add(serviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/customer/services/document.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 170));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 170));

        serviceName8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName8.setForeground(new java.awt.Color(52, 53, 61));
        serviceName8.setText("Fecha solicitud");
        jPanel4.add(serviceName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        serviceName10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName10.setForeground(new java.awt.Color(52, 53, 61));
        serviceName10.setText("Pedido por");
        jPanel4.add(serviceName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        servicePrice.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        servicePrice.setForeground(new java.awt.Color(141, 141, 141));
        servicePrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        servicePrice.setText("Pepito perez");
        jPanel4.add(servicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 200, 20));

        serviceName11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName11.setForeground(new java.awt.Color(52, 53, 61));
        serviceName11.setText("Medio de pago");
        jPanel4.add(serviceName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        servicePaymethod.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        servicePaymethod.setForeground(new java.awt.Color(141, 141, 141));
        servicePaymethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        servicePaymethod.setText("Efectivo");
        jPanel4.add(servicePaymethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 180, 20));

        serviceReturn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceReturn.setForeground(new java.awt.Color(52, 53, 61));
        serviceReturn.setText("Retorno");
        serviceReturn.setEnabled(false);
        jPanel4.add(serviceReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        serviceName9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        serviceName9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceName9.setForeground(new java.awt.Color(52, 53, 61));
        serviceName9.setText("Valor");
        jPanel4.add(serviceName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        serviceDate.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        serviceDate.setForeground(new java.awt.Color(141, 141, 141));
        serviceDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serviceDate.setText("Pepito perez");
        jPanel4.add(serviceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 200, 20));

        servicePrice1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        servicePrice1.setForeground(new java.awt.Color(141, 141, 141));
        servicePrice1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        servicePrice1.setText("Pepito perez");
        jPanel4.add(servicePrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 340, 400));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        subject.notificarObservadores(null, null);
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityAdress;
    private javax.swing.JLabel activityDescription;
    private javax.swing.JLabel activityDetails;
    private javax.swing.JLabel deliverName;
    private javax.swing.JLabel deliverVehicle;
    private java.awt.Label dtails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel serviceDate;
    private java.awt.Label serviceName;
    private java.awt.Label serviceName10;
    private java.awt.Label serviceName11;
    private java.awt.Label serviceName14;
    private java.awt.Label serviceName17;
    private java.awt.Label serviceName18;
    private java.awt.Label serviceName2;
    private java.awt.Label serviceName3;
    private java.awt.Label serviceName5;
    private java.awt.Label serviceName7;
    private java.awt.Label serviceName8;
    private java.awt.Label serviceName9;
    private javax.swing.JLabel servicePaymethod;
    private javax.swing.JLabel servicePrice;
    private javax.swing.JLabel servicePrice1;
    private javax.swing.JCheckBox serviceReturn;
    // End of variables declaration//GEN-END:variables
}
